 /******************************************************************************
 * Module     : sevenSegment
 *
 * File Name  : sevenSegment.c
 *
 * Description: Source file for seven segment driver
 *
 * Author     : Ahmed Abd Elgleel
 *
 * Date	      : Oct 11, 2023
 *******************************************************************************/
#include"seven_segment.h"
#include "gpio_interface.h"

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
* Description :
* Initialize the Seven Segment:
* 	Setup the Seven Segment pins directions by use the GPIO driver.
*/
void SEVENSEGMENT_init(void)
{
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+1, PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+2, PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+3, PIN_OUTPUT);
#ifndef SEVEN_SEGMENT_WITH_DECODER
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+4, PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+5, PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+6, PIN_OUTPUT);
#endif
#ifdef SEVEN_SEGMENT_FIRST_CONTROL_ENABLE_PIN
	GPIO_setupPinDirection(SEVEN_SEGMENT_CONTROL_ENABLE_PORT_ID, SEVEN_SEGMENT_FIRST_CONTROL_ENABLE_PIN, PIN_OUTPUT);
#endif
#ifdef SEVEN_SEGMENT_SECOND_CONTROL_ENABLE_PIN
	GPIO_setupPinDirection(SEVEN_SEGMENT_CONTROL_ENABLE_PORT_ID, SEVEN_SEGMENT_SECOND_CONTROL_ENABLE_PIN, PIN_OUTPUT);
#endif
}

/*
* Description :
* Enable a certain Seven Segment on using multiplixing techique:
*/
void SEVENSEGMENT_enable(uint8 a_sevenSegmentNum)
{

	if(FIRST_SEVEN_SEGMENT==a_sevenSegmentNum)
	{
		GPIO_writePin(SEVEN_SEGMENT_CONTROL_ENABLE_PORT_ID, SEVEN_SEGMENT_FIRST_CONTROL_ENABLE_PIN, CONTROL_ENABLE);
	}
	else if(SECOND_SEVEN_SEGMENT==a_sevenSegmentNum)
	{

		GPIO_writePin(SEVEN_SEGMENT_CONTROL_ENABLE_PORT_ID, SEVEN_SEGMENT_SECOND_CONTROL_ENABLE_PIN, CONTROL_ENABLE);
	}
	else
	{
		/*handling more Control Lines if needed*/
	}

}
/*
* Description :
* disable a certain Seven Segment on using multiplixing techique:
*/
void SEVENSEGMENT_disable(uint8 a_sevenSegmentNum)
{
	if(0==a_sevenSegmentNum)
	{
		GPIO_writePin(SEVEN_SEGMENT_CONTROL_ENABLE_PORT_ID, SEVEN_SEGMENT_FIRST_CONTROL_ENABLE_PIN, CONTROL_DISABLE);
	}
	else if(1==a_sevenSegmentNum)
	{
		GPIO_writePin(SEVEN_SEGMENT_CONTROL_ENABLE_PORT_ID, SEVEN_SEGMENT_SECOND_CONTROL_ENABLE_PIN, CONTROL_DISABLE);
	}
	else
	{
		/*handling more Control Lines if needed*/
	}

}

/*
* Description :
* Display on the Seven Segment without using Decoder:
* 	Display the value on 4 pins by use the GPIO driver.
*/
#ifndef SEVEN_SEGMENT_WITH_DECODER
void SEVENSEGMENT_DisplayWithoutDecoder(uint8 a_value)
{
	switch(a_value)
	{
	case 0 :
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID,TURN_ON_THIS_SEGMENT );
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+1,TURN_ON_THIS_SEGMENT );
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+2,TURN_ON_THIS_SEGMENT );
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+3,TURN_ON_THIS_SEGMENT );
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+4,TURN_ON_THIS_SEGMENT );
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+5,TURN_ON_THIS_SEGMENT );
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+6,TURN_OFF_THIS_SEGMENT);
		break;
	case 1:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+1, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+2, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+3, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+4, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+5, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+6, TURN_OFF_THIS_SEGMENT);
		break;
	case 2:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+1, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+2, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+3, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+4, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+5, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+6, TURN_ON_THIS_SEGMENT);
		break;
	case 3:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+1, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+2, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+3, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+4, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+5, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+6, TURN_ON_THIS_SEGMENT);
		break;
	case 4:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+1, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+2, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+3, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+4, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+5, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+6, TURN_ON_THIS_SEGMENT);
		break;
	case 5:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+1, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+2, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+3, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+4, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+5, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+6, TURN_ON_THIS_SEGMENT);
		break;
	case 6:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+1, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+2, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+3, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+4, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+5, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+6, TURN_ON_THIS_SEGMENT);
		break;
	case 7:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+1, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+2, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+3, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+4, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+5, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+6, TURN_OFF_THIS_SEGMENT);
		break;
	case 8:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+1, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+2, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+3, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+4, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+5, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+6, TURN_ON_THIS_SEGMENT);
		break;
	case 9:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+1, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+2, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+3, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+4, TURN_OFF_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+5, TURN_ON_THIS_SEGMENT);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID+6, TURN_ON_THIS_SEGMENT);
		break;
	default:
		/*Do Nothing*/
		break;
	}
}
#endif
/*
* Description :
* Display on the Seven Segment using Decoder:
* 	Display the value on 4 pins by use the GPIO driver.
*/
#ifdef SEVEN_SEGMENT_WITH_DECODER
void SEVENSEGMENT_DisplayWithDecoder(uint8 a_value)
{
	if(a_value<10)
	{
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, a_value&1);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, a_value&2);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, a_value&4);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_FIRST_PIN_ID, a_value&8);
	}
	else
	{
		/*Do Nothing*/
	}
}
#endif
